[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "jay"
authors = [{name = "Graziella", email = "graziella@jay"}]
dynamic = ["version", "description"]
